server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://10.17.3.193:3100/loki/api/v1/push

scrape_configs:
- job_name: PBL-CSOC
  static_configs:
  - targets:
      - localhost
    labels:
      job: PBL-CSOC
      __path__: /var/log/*log
